#!/bin/bash
configure

set interfaces ethernet eth0 address dhcp
set interfaces ethernet eth0 description 'outside'
set interfaces ethernet eth1 address '192.168.0.1/24'
set interfaces ethernet eth1 description 'inside'

set service dhcp-server shared-network-name labpool subnet 192.168.0.0/24 default-router '192.168.0.1'
set service dhcp-server shared-network-name labpool subnet 192.168.0.0/24 name-server '192.168.0.1'
set service dhcp-server shared-network-name labpool subnet 192.168.0.0/24 lease '86400'
set service dhcp-server shared-network-name labpool subnet 192.168.0.0/24 range 0 start 192.168.0.9
set service dhcp-server shared-network-name labpool subnet 192.168.0.0/24 range 0 stop '192.168.0.254'

set service dns forwarding cache-size '0'
set service dns forwarding listen-address '192.168.0.1'
set service dns forwarding allow-from '192.168.0.0/24'

set nat source rule 100 outbound-interface 'eth0'
set nat source rule 100 source address '192.168.0.0/24'
set nat source rule 100 translation address masquerade
